SET(LIBCORE_SRC_y
./Print.cpp
./wiring_digital.c
./board.c
./RingBuffer.cpp
./wiring_pulse.cpp
./WString.cpp
./new.cpp
./abi.cpp
./avr/dtostrf.c
./main.cpp
./WInterrupts.cpp
./itoa.c
./WSerial.cpp
./Stream.cpp
./pins_arduino.c
./Tone.cpp
./HardwareTimer.cpp
./hooks.c
./WMath.cpp
./wiring_shift.c
./USBSerial.cpp
./wiring_analog.c
./stm32/usb/cdc/usbd_cdc.c
./stm32/usb/cdc/cdc_queue.c
./stm32/usb/cdc/usbd_cdc_if.c
./stm32/usb/usbd_desc.c
./stm32/usb/hid/usbd_hid_composite.c
./stm32/usb/hid/usbd_hid_composite_if.c
./stm32/usb/usb_device_ioreq.c
./stm32/usb/usb_device_core.c
./stm32/usb/usb_device_ctlreq.c
./stm32/usb/usbd_conf.c
./stm32/usb/usbd_ep_conf.c
./stm32/usb/usbd_if.c
./HardwareSerial.cpp
./wiring_time.c
./stm32/startup_stm32yyxx.S
)
#./IPAddress.cpp)

